<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang=""><head>
  <meta charset="utf-8">
  <meta name="generator" content="quarto-0.2.232">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>data_access__harmonize-cloud-non-cloud_andy_to_avoid_merge_conflicts</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>

  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
  <script src="../site_libs/quarto-nav/quarto-nav.js"></script>
  <script src="../site_libs/quarto-nav/headroom.min.js"></script>
  <script src="../site_libs/clipboard/clipboard.min.js"></script>
  <meta name="quarto:offset" content="../">
  <script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
  <script src="../site_libs/quarto-search/fuse.min.js"></script>
  <script src="../site_libs/quarto-search/quarto-search.js"></script>
  <script src="../site_libs/quarto-html/quarto.js"></script>
  <script src="../site_libs/quarto-html/popper.min.js"></script>
  <script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
  <script src="../site_libs/quarto-html/anchor.min.js"></script>
  <link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
  <link class="quarto-color-scheme" href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
  <link class="quarto-color-scheme quarto-color-alternate" rel="prefetch" href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css">
  <script src="../site_libs/bootstrap/bootstrap.min.js"></script>
  <link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
  <link class="quarto-color-scheme" href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
  <link class="quarto-color-scheme quarto-color-alternate" rel="prefetch" href="../site_libs/bootstrap/bootstrap-dark.min.css">
  <script id="quarto-search-options" type="application/json">{
    "location": "sidebar",
    "copy-button": false,
    "collapse-after": 2,
    "panel-placement": "start",
    "type": "textbox",
    "limit": 20
  }</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
  <link rel="stylesheet" href="../styles.css">
</head>
<body>
<div id="quarto-search-results"></div>
<header id="quarto-header" class="headroom fixed-top">
<nav class="quarto-secondary-nav py-2 d-lg-none d-md-block " data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <div class="container-fluid d-flex justify-content-between">
    <h1 class="quarto-secondary-nav-title mb-0 fs-3 d-inline">(Untitled)</h1>
    <button type="button" class="quarto-btn-toggle btn d-lg-none py-0 px-1 d-inline-block border-0 ">
      <i class="bi bi-chevron-right"></i>
    </button>
  </div>
</nav>
</header>
 <!-- /navbar/sidebar -->
<div class="container-fluid quarto-container d-flex flex-column page-layout-article">
<div class="row flex-fill" id="quarto-content">
  <div id="quarto-sidebar" class="col col-12 col-lg-3 d-lg-flex px-0 pt-0 sidebar collapse sidebar-navigation">
    <nav class="me-lg-auto docked overflow-auto">
  <div class="px-3 pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
    <img src="https://user-images.githubusercontent.com/2915555/133525653-2a2278b1-1015-4350-b2a5-160d125aaaf7.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">2021 Cloud Hackathon</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/nasa-openscapes/2021-Cloud-Hackathon" title="" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
  </div>
    <div class="px-3 mt-2 flex-shrink-0 align-items-center">
      <div class="sidebar-search">
      <div id="quarto-search" class="mb-0 " title="Search">
</div>
      </div>
    </div>
  <div class="sidebar-menu-container"> 
  <ul class="list-unstyled mt-1 px-3">
      <li class="sidebar-item">
  <a href="../index.html" class="">Welcome</a>
</li>
      <ul class="list-unstyled sidebar-section depth1">
    <li class="">
        <div class="me-auto">
          <div class="d-inline-flex w-100 sidebar-section-item">
            <div class="sidebar-section-link me-auto">
            <a href="../logistics/index.html" class="">Logistics</a>
            </div>
            <a class="text-start  " data-bs-toggle="collapse" data-bs-target="#logistics-collapse" aria-expanded="true">
              <div><i class="bi bi-chevron-right ms-2"></i></div>
            </a>
            </div>
        </div>
      <div class="collapse  show" id="logistics-collapse">
        <ul class="list-unstyled sidebar-item-contents">
          <li class="sidebar-item">
  <a href="../logistics/schedule.html" class="">Schedule</a>
</li>
          <li class="sidebar-item">
  <a href="../logistics/prerequisites.html" class="">Prerequisites, setup, &amp; getting help</a>
</li>
        </ul>
      </div>
    </li>
  </ul>
      <ul class="list-unstyled sidebar-section depth1">
    <li class="">
        <div class="me-auto">
          <div class="d-inline-flex w-100 sidebar-section-item">
            <div class="sidebar-section-link me-auto">
            <a href="../clinic/index.html" class="">Pre-Hackathon Clinic</a>
            </div>
            <a class="text-start  " data-bs-toggle="collapse" data-bs-target="#pre-hackathonclinic-collapse" aria-expanded="true">
              <div><i class="bi bi-chevron-right ms-2"></i></div>
            </a>
            </div>
        </div>
      <div class="collapse  show" id="pre-hackathonclinic-collapse">
        <ul class="list-unstyled sidebar-item-contents">
          <li class="sidebar-item">
  <a href="../clinic/jupyterhub.html" class="">JupyterHub, repos, environments</a>
</li>
          <li class="sidebar-item">
  <a href="../clinic/notebooks.html" class="">Notebooks, Python, GitHub</a>
</li>
        </ul>
      </div>
    </li>
  </ul>
      <ul class="list-unstyled sidebar-section depth1">
    <li class="">
        <div class="me-auto">
          <div class="d-inline-flex w-100 sidebar-section-item">
            <div class="sidebar-section-link me-auto">
            <a href="../tutorials/index.html" class="">Tutorials</a>
            </div>
            <a class="text-start  " data-bs-toggle="collapse" data-bs-target="#tutorials-collapse" aria-expanded="true">
              <div><i class="bi bi-chevron-right ms-2"></i></div>
            </a>
            </div>
        </div>
      <div class="collapse  show" id="tutorials-collapse">
        <ul class="list-unstyled sidebar-item-contents">
          <li class="sidebar-item">
  <a href="../tutorials/getting-set-up.html" class="">Getting set up and connected</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Data_discovery_with_cmr.html" class="">Data discovery with CMR</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Data_Discovery__CMR-STAC_API.html" class="">Data Discovery: CMR-STAC API</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Introduction_to_xarray.html" class="">An Introductionto <code>xarray</code></a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/NASA_Earthdata_Authentication.html" class="">Authentication for NASA Earthdata</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Data_Access__Direct_S3_Access.html" class="">Direct S3 Data Access</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Data_Access__Direct_S3_Access__PODAAC_ECCO_SSH.html" class="">Direct S3 Data Access - Rough PODAAC ECCO SSH Example</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Data_Access__Harmonize-cloud-non-cloud.html" class="">Harmonizing data located within and outside of the NASA Earthdata Cloud</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Data_Access__Harmony_Subsetting.html" class="">Data Subsetting and Transformation Services in the Cloud</a>
</li>
        </ul>
      </div>
    </li>
  </ul>
      <li class="sidebar-item">
  <a href="../tutorials-templates/index.html" class="">Tutorial Templates</a>
</li>
      <ul class="list-unstyled sidebar-section depth1">
    <li class="">
        <div class="me-auto">
          <div class="d-inline-flex w-100 sidebar-section-item">
            <div class="sidebar-section-link me-auto">
            <a href="../projects/index.html" class="">Projects</a>
            </div>
            <a class="text-start  " data-bs-toggle="collapse" data-bs-target="#projects-collapse" aria-expanded="true">
              <div><i class="bi bi-chevron-right ms-2"></i></div>
            </a>
            </div>
        </div>
      <div class="collapse  show" id="projects-collapse">
        <ul class="list-unstyled sidebar-item-contents">
          <li class="sidebar-item">
  <a href="../projects/hacking.html" class="">Hacking at the Cloud Hackathon</a>
</li>
          <li class="sidebar-item">
  <a href="../projects/hackathon-projects.html" class="">Hackathon Projects</a>
</li>
        </ul>
      </div>
    </li>
  </ul>
      <ul class="list-unstyled sidebar-section depth1">
    <li class="">
        <div class="me-auto">
            <a class="sidebar-section-item d-inline-flex text-start w-100 " data-bs-toggle="collapse" data-bs-target="#additionalresources-collapse" aria-expanded="true">
              <div class="me-auto sidebar-section-item">Additional Resources</div>
            <div><i class="bi bi-chevron-right ms-2"></i></div>
            </a>
        </div>
      <div class="collapse  show" id="additionalresources-collapse">
        <ul class="list-unstyled sidebar-item-contents">
          <li class="sidebar-item">
  <a href="../tutorials/Additional_Resources__Direct_S3_Access__gdalvrt.html" class="">Direct S3 Data Access with GDAL Virtual Raster Format (VRT)</a>
</li>
          <li class="sidebar-item">
  <a href="../tutorials/Additional_Resources__Direct_S3_Access__rioxarray_clipping.html" class="">Direct S3 Data Access</a>
</li>
        </ul>
      </div>
    </li>
  </ul>
  </ul>
  </div>
</nav>
  </div>
  <div id="quarto-toc-sidebar" class=" pt-0 col col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-toc order-last"><nav id="TOC" role="doc-toc">
<h2 id="toc-title">On this page</h2>
<ul>
<li><a href="#harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud" class="nav-link active" data-scroll-target="#harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud">Harmonizing data located within and outside of the NASA Earthdata Cloud</a>
<ul class="collapse">
<li><a href="#summary" class="nav-link" data-scroll-target="#summary">Summary</a>
<ul class="collapse">
<li><a href="#objectives" class="nav-link" data-scroll-target="#objectives">Objectives</a></li>
<li><a href="#import-packages" class="nav-link" data-scroll-target="#import-packages">Import packages</a></li>
<li><a href="#determine-storage-location-of-datasets-of-interest" class="nav-link" data-scroll-target="#determine-storage-location-of-datasets-of-interest">Determine storage location of datasets of interest</a></li>
<li><a href="#declare-datasets-of-interest" class="nav-link" data-scroll-target="#declare-datasets-of-interest">Declare datasets of interest</a></li>
<li><a href="#download-icesat-2-atl03-granule" class="nav-link" data-scroll-target="#download-icesat-2-atl03-granule">Download ICESat-2 ATL03 granule</a></li>
<li><a href="#determine-variables-of-interest-sst-ocean-color-chemistry" class="nav-link" data-scroll-target="#determine-variables-of-interest-sst-ocean-color-chemistry">Determine variables of interest: SST, ocean color, chemistry…</a></li>
<li><a href="#pull-those-variables-into-xarray-in-place" class="nav-link" data-scroll-target="#pull-those-variables-into-xarray-in-place">Pull those variables into xarray “in place”</a></li>
<li><a href="#get-s3-credentials" class="nav-link" data-scroll-target="#get-s3-credentials">Get S3 credentials</a></li>
<li><a href="#open-a-s3-file" class="nav-link" data-scroll-target="#open-a-s3-file">Open a s3 file</a></li>
<li><a href="#use-geolocation-of-icesat-2-to-define-the-single-transect-used-to-pull-coincident-ocean-data-out-from-array" class="nav-link" data-scroll-target="#use-geolocation-of-icesat-2-to-define-the-single-transect-used-to-pull-coincident-ocean-data-out-from-array">Use geolocation of ICESat-2 to define the single transect used to pull coincident ocean data out from array</a></li>
<li><a href="#create-a-plot-of-the-single-transect-of-gridded-data" class="nav-link" data-scroll-target="#create-a-plot-of-the-single-transect-of-gridded-data">Create a plot of the single transect of gridded data</a></li>
</ul></li>
<li><a href="#download-modis-ghrsst-data-from-cloud" class="nav-link" data-scroll-target="#download-modis-ghrsst-data-from-cloud">Download MODIS GHRSST data from Cloud</a></li>
<li><a href="#resources-optional" class="nav-link" data-scroll-target="#resources-optional">Resources (optional)</a></li>
<li><a href="#conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
</ul></li>
</ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/nasa-openscapes/2021-Cloud-Hackathon/edit/main/tutorials/Data_Access__Harmonize-cloud-non-cloud_andy_to_avoid_merge_conflicts.ipynb" class="toc-action">Edit this page</a></p><p><a href="https://github.com/nasa-openscapes/2021-Cloud-Hackathon/issues/new" class="toc-action">Report an issue</a></p></div></div></nav></div>
  <div class="col mx-auto col-sm-12 col-md-9 col-lg-7 col-xl-7 px-lg-4 pe-xxl-4 ps-xxl-0">
<main>

<section id="harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud" class="level1">
<h1>Harmonizing data located within and outside of the NASA Earthdata Cloud</h1>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This tutorial will combine several workflow steps and components from the previous days, demonstrating the process of using the geolocation of data available outside of the Earthdata Cloud to then access coincident variables of cloud-accessible data. This may be a common use case as NASA Earthdata continues to migrate to the cloud, producing a “hybrid” data archive across Amazon Web Services (AWS) and original on-premise data storage systems. Additionally, you may also want to combine field measurements with remote sensing data available on the Earthdata Cloud.</p>
<p>This specific example explores the harmonization of the ICESat-2 ATL03 data product, currently (as of November 2021) available publicaly via direct download at the NSIDC DAAC, with Sea Surface Temperature variables available from PO.DAAC on the Earthdata Cloud.</p>
<section id="objectives" class="level3">
<h3 class="anchored" data-anchor-id="objectives">Objectives</h3>
<hr>
</section>
<section id="import-packages" class="level3">
<h3 class="anchored" data-anchor-id="import-packages">Import packages</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> netrc</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pprint <span class="im">import</span> pprint</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> s3fs</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xarray <span class="im">as</span> xr</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cartopy.crs <span class="im">as</span> ccrs</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># packages below here are not used</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">#from xml.etree import ElementTree as ET</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#import time</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#import zipfile</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#import io</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">#import shutil</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">#import json</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">#from urllib import request</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="determine-storage-location-of-datasets-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="determine-storage-location-of-datasets-of-interest">Determine storage location of datasets of interest</h3>
<p>First, let’s see whether our datasets of interest reside in the Earthdata Cloud or whether they reside on premise, or “on prem” at a local data center.</p>
<p>Background from CMR API (consider removing): The cloud_hosted parameter can be set to “true” or “false”. When true, the results will be restricted to collections that have a DirectDistributionInformation element or have been tagged with gov.nasa.earthdatacloud.s3. curl “https://cmr.earthdata.nasa.gov/search/collections?cloud_hosted=true”</p>
</section>
<section id="declare-datasets-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="declare-datasets-of-interest">Declare datasets of interest</h3>
<p>Identify the dataset ID that is used internally within CMR to designate each dataset</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>modis_name <span class="op">=</span> <span class="st">'MODIS_T-JPL-L2P-v2019.0'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>icesat2_name <span class="op">=</span> <span class="st">'ATL03'</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># icesat2_id = 'C1997321091-NSIDC_ECS'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-execution_count="4">
<div class="sourceCode" id="cb3"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>CMR_OPS <span class="op">=</span> <span class="st">'https://cmr.earthdata.nasa.gov/search'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="ss">f'</span><span class="sc">{</span>CMR_OPS<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span><span class="st">"collections"</span><span class="sc">}</span><span class="ss">'</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(url, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'short_name'</span>: modis_name,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>collections <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> collection <span class="kw">in</span> collections:</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>collection[<span class="st">"id"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"version:"</span><span class="sc">}{</span>collection[<span class="st">"version_id"</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>C1940475563-POCLOUD version:2019.0
C1693233387-PODAAC version:2019.0</code></pre>
</div>
</div>
<p>Start with the MODIS dataset, setting the <code>cloud_hosted</code> parameter to True:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode" id="cb5"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(url, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'concept_id'</span>: <span class="st">'C1940475563-POCLOUD'</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'cloud_hosted'</span>: <span class="st">'True'</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.status_code)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.headers[<span class="st">'CMR-Hits'</span>])</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>collections <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>pprint(collections)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>200
1
[{'archive_center': 'NASA/JPL/PODAAC',
  'associations': {'services': ['S1962070864-POCLOUD', 'S2004184019-POCLOUD'],
                   'tools': ['TL2108419875-POCLOUD', 'TL2092786348-POCLOUD'],
                   'variables': ['V1997811750-POCLOUD',
                                 'V1997811794-POCLOUD',
                                 'V2112014697-POCLOUD',
                                 'V1997811877-POCLOUD',
                                 'V1997811902-POCLOUD',
                                 'V2028668027-POCLOUD',
                                 'V2028632036-POCLOUD',
                                 'V1997811775-POCLOUD',
                                 'V1997811764-POCLOUD',
                                 'V1997811783-POCLOUD',
                                 'V2112014702-POCLOUD',
                                 'V2028632034-POCLOUD',
                                 'V2112014700-POCLOUD',
                                 'V1997811759-POCLOUD',
                                 'V2028632038-POCLOUD']},
  'boxes': ['-90 -180 90 180'],
  'browse_flag': True,
  'collection_data_type': 'SCIENCE_QUALITY',
  'coordinate_system': 'CARTESIAN',
  'data_center': 'POCLOUD',
  'dataset_id': 'GHRSST Level 2P Global Sea Surface Skin Temperature from the '
                'Moderate Resolution Imaging Spectroradiometer (MODIS) on the '
                'NASA Terra satellite (GDS2)',
  'has_formats': True,
  'has_spatial_subsetting': True,
  'has_temporal_subsetting': True,
  'has_transforms': False,
  'has_variables': True,
  'id': 'C1940475563-POCLOUD',
  'links': [{'href': 'https://podaac-tools.jpl.nasa.gov/drive/files/OceanTemperature/ghrsst/docs/GDS20r5.pdf',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://oceancolor.gsfc.nasa.gov/atbd/sst4/',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://oceancolor.gsfc.nasa.gov/reprocessing/r2019/sst/',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://oceancolor.gsfc.nasa.gov/atbd/sst/flag/',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://ghrsst.jpl.nasa.gov',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://modis.gsfc.nasa.gov/data/atbd/atbd_mod25.pdf',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://podaac.jpl.nasa.gov/Podaac/thumbnails/MODIS_T-JPL-L2P-v2019.0.jpg',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/browse#'},
            {'href': 'https://podaac.jpl.nasa.gov/forum/viewforum.php?f=18&amp;sid=e2d67e5a01815fc6e39fcd2087ed8bc8',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://oceancolor.gsfc.nasa.gov/atbd/sst/',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://github.com/podaac/data-readers',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'http://www.ghrsst.org',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://podaac.jpl.nasa.gov/CitingPODAAC',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': ' '
                     'https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1940475563-POCLOUD',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/data#'},
            {'href': 'https://github.com/podaac/tutorials/blob/master/notebooks/MODIS_L2P_SST_DataCube.ipynb',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'},
            {'href': 'https://search.earthdata.nasa.gov/search/granules?p=C1940475563-POCLOUD',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/data#'}],
  'online_access_flag': True,
  'orbit_parameters': {'inclination_angle': '98.2',
                       'number_of_orbits': '1.0',
                       'period': '98.8',
                       'swath_width': '2330.0'},
  'organizations': ['NASA/JPL/PODAAC'],
  'original_format': 'UMM_JSON',
  'platforms': ['Terra'],
  'processing_level_id': '2',
  'service_features': {'esi': {'has_formats': False,
                               'has_spatial_subsetting': False,
                               'has_temporal_subsetting': False,
                               'has_transforms': False,
                               'has_variables': False},
                       'harmony': {'has_formats': True,
                                   'has_spatial_subsetting': True,
                                   'has_temporal_subsetting': True,
                                   'has_transforms': False,
                                   'has_variables': True},
                       'opendap': {'has_formats': True,
                                   'has_spatial_subsetting': True,
                                   'has_temporal_subsetting': True,
                                   'has_transforms': False,
                                   'has_variables': True}},
  'short_name': 'MODIS_T-JPL-L2P-v2019.0',
  'summary': 'NASA produces skin sea surface temperature (SST) products from '
             'the Infrared (IR) channels of the Moderate-resolution Imaging '
             'Spectroradiometer (MODIS) onboard the Terra satellite. Terra was '
             'launched by NASA on December 18, 1999, into a sun synchronous, '
             'polar orbit with a daylight descending node at 10:30 am, to '
             'study the global dynamics of the Earth atmosphere, land and '
             'oceans. The MODIS captures data in 36 spectral bands at a '
             'variety of spatial resolutions.  Two SST products can be present '
             'in these files. The first is a skin SST produced for both day '
             'and night observations, derived from the long wave IR 11 and 12 '
             'micron wavelength channels, using a modified nonlinear SST '
             'algorithm intended to provide continuity with SST derived from '
             'heritage and current NASA sensors. At night, a second SST '
             'product is produced using the mid-infrared 3.95 and 4.05 micron '
             'channels which are unique to MODIS; the SST derived from these '
             'measurements is identified as SST4. The SST4 product has lower '
             'uncertainty, but due to sun glint can only be produced at night. '
             'MODIS L2P SST data have a 1 km spatial resolution at nadir and '
             'are stored in 288 five minute granules per day. Full global '
             'coverage is obtained every two days, with coverage poleward of '
             '32.3 degree being complete each day. The production of MODIS L2P '
             'SST files is part of the Group for High Resolution Sea Surface '
             'Temperature (GHRSST) project, and is a joint collaboration '
             'between the NASA Jet Propulsion Laboratory (JPL), the NASA Ocean '
             'Biology Processing Group (OBPG), and the Rosenstiel School of '
             'Marine and Atmospheric Science (RSMAS). Researchers at RSMAS are '
             'responsible for SST algorithm development, error statistics and '
             'quality flagging, while the OBPG, as the NASA ground data '
             'system, is responsible for the production of daily MODIS ocean '
             'products. JPL acquires MODIS ocean granules from the OBPG and '
             'reformats them to the GHRSST L2P netCDF specification with '
             'complete metadata and ancillary variables, and distributes the '
             'data as the official Physical Oceanography Data Archive '
             '(PO.DAAC) for SST.  The R2019.0 supersedes the previous R2014.0 '
             'datasets which can be found at  '
             'https://doi.org/10.5067/GHMDT-2PJ02',
  'time_start': '2000-02-24T00:00:00.000Z',
  'title': 'GHRSST Level 2P Global Sea Surface Skin Temperature from the '
           'Moderate Resolution Imaging Spectroradiometer (MODIS) on the NASA '
           'Terra satellite (GDS2)',
  'updated': '2019-12-31T19:19:57.627Z',
  'version_id': '2019.0'}]</code></pre>
</div>
</div>
<p>Now we will try our ICESat-2 dataset to see what id’s are returned for a given dataset name.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode" id="cb7"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(url, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'short_name'</span>: icesat2_name,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>collections <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># pprint(collections)</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> collection <span class="kw">in</span> collections:</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>collection[<span class="st">"id"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"version:"</span><span class="sc">}{</span>collection[<span class="st">"version_id"</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>C1705401930-NSIDC_ECS version:003
C1997321091-NSIDC_ECS version:004</code></pre>
</div>
</div>
<p>Two separate datasets exist in the CMR. Now let’s take each ID, setting the <code>cloud_hosted</code> parameter to True, to identify which dataset is cloud-hosted:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode" id="cb9"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>CMR_OPS <span class="op">=</span> <span class="st">'https://cmr.earthdata.nasa.gov/search'</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="ss">f'</span><span class="sc">{</span>CMR_OPS<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span><span class="st">"collections"</span><span class="sc">}</span><span class="ss">'</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(url, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'concept_id'</span>: <span class="st">'C1997321091-NSIDC_ECS'</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'cloud_hosted'</span>: <span class="st">'False'</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Status code: </span><span class="sc">{</span>response<span class="sc">.</span>status_code<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Hits: </span><span class="sc">{</span>response<span class="sc">.</span>headers[<span class="st">"CMR-Hits"</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>collections <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>pprint(collections)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>Status code: 200
Hits: 1
[{'archive_center': 'NASA NSIDC DAAC',
  'associations': {'services': ['S1568899363-NSIDC_ECS',
                                'S1613689509-NSIDC_ECS',
                                'S1977894169-NSIDC_ECS',
                                'S2013502342-NSIDC_ECS'],
                   'tools': ['TL1950215144-NSIDC_ECS',
                             'TL1977971361-NSIDC_ECS',
                             'TL1993837300-NSIDC_ECS',
                             'TL1952642907-NSIDC_ECS']},
  'boxes': ['-90 -180 90 180'],
  'browse_flag': False,
  'coordinate_system': 'CARTESIAN',
  'data_center': 'NSIDC_ECS',
  'dataset_id': 'ATLAS/ICESat-2 L2A Global Geolocated Photon Data V004',
  'has_formats': True,
  'has_spatial_subsetting': True,
  'has_temporal_subsetting': True,
  'has_transforms': False,
  'has_variables': True,
  'id': 'C1997321091-NSIDC_ECS',
  'links': [{'href': 'https://n5eil01u.ecs.nsidc.org/ATLAS/ATL03.004/',
             'hreflang': 'en-US',
             'length': '0.0KB',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/data#'},
            {'href': 'https://search.earthdata.nasa.gov/search/granules?p=C1997321091-NSIDC_ECS&amp;pg[0][gsk]=-start_date&amp;q=atl03%20v004&amp;tl=1602518008!4!!&amp;m=-9.278314769606354!-105.46875!1!1!0!0%2C2',
             'hreflang': 'en-US',
             'length': '0.0KB',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/data#'},
            {'href': 'http://openaltimetry.org/',
             'hreflang': 'en-US',
             'length': '0.0KB',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/data#'},
            {'href': 'https://nsidc.org/data/data-access-tool/ATL03/versions/4/',
             'hreflang': 'en-US',
             'length': '0.0KB',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/data#'},
            {'href': 'https://doi.org/10.5067/ATLAS/ATL03.004',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/metadata#'},
            {'href': 'https://doi.org/10.5067/ATLAS/ATL03.004',
             'hreflang': 'en-US',
             'rel': 'http://esipfed.org/ns/fedsearch/1.1/documentation#'}],
  'online_access_flag': True,
  'orbit_parameters': {'inclination_angle': '92.0',
                       'number_of_orbits': '0.071428571',
                       'period': '96.8',
                       'start_circular_latitude': '0.0',
                       'swath_width': '36.0'},
  'organizations': ['NASA NSIDC DAAC', 'NASA/GSFC/EOS/ESDIS'],
  'original_format': 'ISO19115',
  'platforms': ['ICESat-2'],
  'processing_level_id': 'Level 2A',
  'service_features': {'esi': {'has_formats': True,
                               'has_spatial_subsetting': True,
                               'has_temporal_subsetting': True,
                               'has_transforms': False,
                               'has_variables': True},
                       'harmony': {'has_formats': False,
                                   'has_spatial_subsetting': False,
                                   'has_temporal_subsetting': False,
                                   'has_transforms': False,
                                   'has_variables': False},
                       'opendap': {'has_formats': False,
                                   'has_spatial_subsetting': False,
                                   'has_temporal_subsetting': False,
                                   'has_transforms': False,
                                   'has_variables': False}},
  'short_name': 'ATL03',
  'summary': 'This data set (ATL03) contains height above the WGS 84 ellipsoid '
             '(ITRF2014 reference frame), latitude, longitude, and time for '
             'all photons downlinked by the Advanced Topographic Laser '
             'Altimeter System (ATLAS) instrument on board the Ice, Cloud and '
             'land Elevation Satellite-2 (ICESat-2) observatory. The ATL03 '
             'product was designed to be a single source for all photon data '
             'and ancillary information needed by higher-level ATLAS/ICESat-2 '
             'products. As such, it also includes spacecraft and instrument '
             'parameters and ancillary data not explicitly required for ATL03.',
  'time_start': '2018-10-13T00:00:00.000Z',
  'title': 'ATLAS/ICESat-2 L2A Global Geolocated Photon Data V004',
  'version_id': '004'}]</code></pre>
</div>
</div>
<p>What happens if we comment out this parameter? Do we see results returned? [TODO: Add instructions on how to comment lines using command slash]<br>
<strong>It would make more sense to set <code>cloud_hosted</code> to False</strong></p>
<p><strong>I suggest saving the ATL03 concept ID and the MODIS GHRSST concept ID to a variables</strong></p>
<pre><code>icesat2_concept_id = 'C1997321091-NSIDC_ECS'
modis_concept_id = 'C1940475563-POCLOUD'</code></pre>
<p>Now we have determined that our Sentinel dataset is provided in the cloud, whereas the ICESat-2 dataset remains “on premise”, residing in a local data center.</p>
<section id="specify-time-range-and-area-of-interest" class="level4">
<h4 class="anchored" data-anchor-id="specify-time-range-and-area-of-interest">Specify time range and area of interest</h4>
<p>We are going to focus on getting data for an area north of Greenland for a single day in June.</p>
<p>These <code>bounding_box</code> and <code>temporal</code> variables will be used for data search, subset, and access below</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bounding Box spatial parameter in decimal degree 'W,S,E,N' format.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>bounding_box <span class="op">=</span> <span class="st">'-62.8,81.7,-56.4,83'</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Each date in yyyy-MM-ddTHH:mm:ssZ format; date range in start,end format</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>temporal <span class="op">=</span> <span class="st">'2019-06-22T00:00:00Z,2019-06-22T23:59:59Z'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-execution_count="9">
<div class="sourceCode" id="cb13"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="ss">f'</span><span class="sc">{</span>CMR_OPS<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span><span class="st">"granules"</span><span class="sc">}</span><span class="ss">'</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(url, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'concept_id'</span>: <span class="st">'C1997321091-NSIDC_ECS'</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'temporal'</span>: temporal,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'bounding_box'</span>: bounding_box,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'page_size'</span>: <span class="dv">200</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.headers[<span class="st">'CMR-Hits'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>2</code></pre>
</div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode" id="cb15"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>granules <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> granule <span class="kw">in</span> granules:</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>granule[<span class="st">"producer_granule_id"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>granule[<span class="st">"granule_size"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>granule[<span class="st">"links"</span>][<span class="dv">0</span>][<span class="st">"href"</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>ATL03_20190622061415_12980304_004_01.h5 1825.3746356964 https://n5eil01u.ecs.nsidc.org/DP9/ATLAS/ATL03.004/2019.06.22/ATL03_20190622061415_12980304_004_01.h5
ATL03_20190622202251_13070304_004_01.h5 3035.5987443924 https://n5eil01u.ecs.nsidc.org/DP9/ATLAS/ATL03.004/2019.06.22/ATL03_20190622202251_13070304_004_01.h5</code></pre>
</div>
</div>
</section>
</section>
<section id="download-icesat-2-atl03-granule" class="level3">
<h3 class="anchored" data-anchor-id="download-icesat-2-atl03-granule">Download ICESat-2 ATL03 granule</h3>
<p>We’ve found 2 granules. We’ll download the first one and write it to a file with the same name as the <code>producer_granule_id</code>.</p>
<p>We need the url for the granule as well. This is <code>href</code> links we printed out above.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>icesat_id <span class="op">=</span> granules[<span class="dv">0</span>][<span class="st">"producer_granule_id"</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>icesat_url <span class="op">=</span> granules[<span class="dv">0</span>][<span class="st">'links'</span>][<span class="dv">0</span>][<span class="st">'href'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>You need Earthdata login credentials to download data from NASA DAACs. These are the credentials you stored in the <code>.netrc</code> file you setup in previous tutorials.</p>
<p>We’ll use the <code>netrc</code> package to retrieve your login and password without exposing them.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>info <span class="op">=</span> netrc.netrc()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>login, account, password <span class="op">=</span> info.authenticators(<span class="st">'urs.earthdata.nasa.gov'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>To retrieve the granule data, we use the <code>requests.get()</code> method, passing Earthdata login credentials as a <code>tuple</code> using the <code>auth</code> keyword.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> requests.get(icesat_url, auth<span class="op">=</span>(login, password))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The response returned by requests has the same structure as all the other responses: a header and contents. The header information has information about the response, including the size of the data we downloaded in bytes.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> r.headers.items():</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The contents needs to be saved to a file. To keep the directory clean, we will create a <code>downloads</code> directory to store the file. We can use a shell command to do this or use the <code>mkdir</code> method from the <code>os</code> package.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>os.mkdir(<span class="st">'downloads'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>You should see a <code>downloads</code> directory in the file browser.</p>
<p>To write the data to a file, we use <code>open</code> to open a file. We need to specify that the file is open for writing by using the <em>write-mode</em> <code>w</code>. We also need to specify that we want to write bytes by setting the <em>binary-mode</em> <code>b</code>. This is important because the response contents are bytes. The default mode for <code>open</code> is <code>text-mode</code>. So make sure you use <code>b</code>.</p>
<p>We’ll use the <code>with</code> statement <em>context-manager</em> to open the file, write the contents of the response, and then close the file. Once the data in <code>r.content</code> is written sucessfully to the file, or if there is an error, the file is closed by the <em>context-manager</em>.</p>
<p>We also need to prepend the <code>downloads</code> path to the filename. We do this using <code>Path</code> from the <code>pathlib</code> package in the standard library.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>outfile <span class="op">=</span> Path(<span class="st">'downloads'</span>, icesat_id)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(outfile, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    f.write(r.content)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Check to make sure it is downloaded.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ls <span class="op">-</span>l .<span class="op">/</span>downloads</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>ATL03_20190622061415_12980304_004_01.h5</code> is an HDF5 file. <code>xarray</code> can open this but you need to tell it which group to read the data from. In this case we read the height data for ground-track 1 left-beam.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode" id="cb24"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>outfile <span class="op">=</span> Path(<span class="st">'downloads'</span>, icesat_id)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> xr.open_dataset(outfile, group<span class="op">=</span><span class="st">'/gt1l/heights'</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display" data-execution_count="14">
<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:         (delta_time: 19219882, ds_surf_type: 5)
Coordinates:
  * delta_time      (delta_time) datetime64[ns] 2019-06-22T06:14:14.882866488...
    lat_ph          (delta_time) float64 ...
    lon_ph          (delta_time) float64 ...
Dimensions without coordinates: ds_surf_type
Data variables:
    dist_ph_across  (delta_time) float32 ...
    dist_ph_along   (delta_time) float32 ...
    h_ph            (delta_time) float32 ...
    pce_mframe_cnt  (delta_time) uint32 ...
    ph_id_channel   (delta_time) uint8 ...
    ph_id_count     (delta_time) int8 ...
    ph_id_pulse     (delta_time) uint8 ...
    quality_ph      (delta_time) int8 ...
    signal_conf_ph  (delta_time, ds_surf_type) int8 ...
Attributes:
    Description:  Contains arrays of the parameters for each received photon.
    data_rate:    Data are stored at the photon detection rate.</pre><div class="xr-wrap" hidden=""><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-556852bc-d1e0-494a-b37a-a17f91380dbe" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-556852bc-d1e0-494a-b37a-a17f91380dbe" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">delta_time</span>: 19219882</li><li><span>ds_surf_type</span>: 5</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-4fb3adc8-3ef6-45ba-bdf9-c7cfa5c50c55" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-4fb3adc8-3ef6-45ba-bdf9-c7cfa5c50c55" class="xr-section-summary">Coordinates: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">delta_time</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">2019-06-22T06:14:14.882866488 .....</div><input id="attrs-32b2ae15-476f-4974-b5e5-ca7f778d4ed9" class="xr-var-attrs-in" type="checkbox"><label for="attrs-32b2ae15-476f-4974-b5e5-ca7f778d4ed9" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c900c837-1a0b-4389-8e6f-06485cb7c583" class="xr-var-data-in" type="checkbox"><label for="data-c900c837-1a0b-4389-8e6f-06485cb7c583" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Elapsed GPS seconds</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>source :</span></dt><dd>Operations</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>description :</span></dt><dd>The transmit time of a given photon, measured in seconds from the ATLAS Standard Data Product Epoch. Note that multiple received photons associated with a single transmit pulse will have the same delta_time. The ATLAS Standard Data Products (SDP) epoch offset is defined within /ancillary_data/atlas_sdp_gps_epoch as the number of GPS seconds between the GPS epoch (1980-01-06T00:00:00.000000Z UTC) and the ATLAS SDP epoch. By adding the offset contained within atlas_sdp_gps_epoch to delta time parameters, the time in gps_seconds relative to the GPS epoch can be computed.</dd></dl></div><div class="xr-var-data"><pre>array(['2019-06-22T06:14:14.882866488', '2019-06-22T06:14:14.882866488',
       '2019-06-22T06:14:14.882866488', ..., '2019-06-22T06:19:24.064273608',
       '2019-06-22T06:19:24.064273608', '2019-06-22T06:19:24.064273608'],
      dtype='datetime64[ns]')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>lat_ph</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-7ea870c6-dea4-4bb1-a253-905678eb3b97" class="xr-var-attrs-in" type="checkbox"><label for="attrs-7ea870c6-dea4-4bb1-a253-905678eb3b97" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-030ada7b-34b1-4627-a243-38e54603d4c4" class="xr-var-data-in" type="checkbox"><label for="data-030ada7b-34b1-4627-a243-38e54603d4c4" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Latitude</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degrees_north</dd><dt><span>source :</span></dt><dd>ATL03g ATBD, Section 3.4</dd><dt><span>valid_min :</span></dt><dd>-90.0</dd><dt><span>valid_max :</span></dt><dd>90.0</dd><dt><span>contentType :</span></dt><dd>modelResult</dd><dt><span>description :</span></dt><dd>Latitude of each received photon. Computed from the ECF Cartesian coordinates of the bounce point.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=float64]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>lon_ph</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-9bde3fec-54a3-4772-beb2-ce7b711a0de8" class="xr-var-attrs-in" type="checkbox"><label for="attrs-9bde3fec-54a3-4772-beb2-ce7b711a0de8" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-dd574bc5-0e48-4d0a-994a-d749bc1b8952" class="xr-var-data-in" type="checkbox"><label for="data-dd574bc5-0e48-4d0a-994a-d749bc1b8952" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Longitude</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degrees_east</dd><dt><span>source :</span></dt><dd>ATL03g ATBD, Section 3.4</dd><dt><span>valid_min :</span></dt><dd>-180.0</dd><dt><span>valid_max :</span></dt><dd>180.0</dd><dt><span>contentType :</span></dt><dd>modelResult</dd><dt><span>description :</span></dt><dd>Longitude of each received photon. Computed from the ECF Cartesian coordinates of the bounce point.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=float64]</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-9635b96b-60fa-4b64-aa10-a904de0fb9fd" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-9635b96b-60fa-4b64-aa10-a904de0fb9fd" class="xr-section-summary">Data variables: <span>(9)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>dist_ph_across</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-fc024c19-65c2-43fc-bb37-a30398f0697c" class="xr-var-attrs-in" type="checkbox"><label for="attrs-fc024c19-65c2-43fc-bb37-a30398f0697c" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-cde1d271-a2b0-4f40-b8b1-226446eb89c6" class="xr-var-data-in" type="checkbox"><label for="data-cde1d271-a2b0-4f40-b8b1-226446eb89c6" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Distance off RGT.</dd><dt><span>units :</span></dt><dd>meters</dd><dt><span>source :</span></dt><dd>ATL03 ATBD, Section 3.1</dd><dt><span>contentType :</span></dt><dd>modelResult</dd><dt><span>description :</span></dt><dd>Across-track distance projected to the ellipsoid of the received photon from the reference ground track.  This is based on the Along-Track Segment algorithm described in Section 3.1.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>dist_ph_along</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-382b16f4-d2e5-40e8-bbe0-e6d735f64c17" class="xr-var-attrs-in" type="checkbox"><label for="attrs-382b16f4-d2e5-40e8-bbe0-e6d735f64c17" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-b1c72b94-e4ef-428e-ba8c-55552c932e2a" class="xr-var-data-in" type="checkbox"><label for="data-b1c72b94-e4ef-428e-ba8c-55552c932e2a" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Distance from equator crossing.</dd><dt><span>units :</span></dt><dd>meters</dd><dt><span>source :</span></dt><dd>ATL03 ATBD, Section 3.1</dd><dt><span>contentType :</span></dt><dd>modelResult</dd><dt><span>description :</span></dt><dd>Along-track distance in a segment projected to the ellipsoid of the received photon, based on the Along-Track Segment algorithm.  Total along track distance can be found by adding this value to the sum of segment lengths measured from the start of the most recent reference groundtrack.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>h_ph</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-1a2a2e6e-cdde-4838-bb41-cb9d5b77b01a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-1a2a2e6e-cdde-4838-bb41-cb9d5b77b01a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-84e888f3-1a4f-4348-bb8b-396c9b363f1d" class="xr-var-data-in" type="checkbox"><label for="data-84e888f3-1a4f-4348-bb8b-396c9b363f1d" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Photon WGS84 Height</dd><dt><span>standard_name :</span></dt><dd>height</dd><dt><span>units :</span></dt><dd>meters</dd><dt><span>source :</span></dt><dd>ATL03g ATBD, Section 3.4</dd><dt><span>contentType :</span></dt><dd>physicalMeasurement</dd><dt><span>description :</span></dt><dd>Height of each received photon, relative to the WGS-84 ellipsoid including the geophysical corrections noted in Section 6. Please note that neither the geoid, ocean tide nor the dynamic atmosphere (DAC) corrections are applied to the ellipsoidal heights.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>pce_mframe_cnt</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">uint32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-68cf99d0-db16-49f7-915a-c4604349a15f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-68cf99d0-db16-49f7-915a-c4604349a15f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-96d713b8-6299-46dc-b629-274383876177" class="xr-var-data-in" type="checkbox"><label for="data-96d713b8-6299-46dc-b629-274383876177" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>PCE Major frame counter</dd><dt><span>units :</span></dt><dd>counts</dd><dt><span>source :</span></dt><dd>Retained from prior a_alt_science_ph packet</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>description :</span></dt><dd>The major frame counter is read from the digital flow controller in a given PCE card.  The counter identifies individual major frames across diag and science packets. Used as part of the photon ID.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=uint32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>ph_id_channel</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">uint8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-3eeb80ab-37f1-492f-af65-d4c28465cfac" class="xr-var-attrs-in" type="checkbox"><label for="attrs-3eeb80ab-37f1-492f-af65-d4c28465cfac" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-603f2671-8bab-43de-b07c-1044130e0abb" class="xr-var-data-in" type="checkbox"><label for="data-603f2671-8bab-43de-b07c-1044130e0abb" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Receive channel id</dd><dt><span>units :</span></dt><dd>1</dd><dt><span>source :</span></dt><dd>Derived as part of Photon ID</dd><dt><span>valid_min :</span></dt><dd>1</dd><dt><span>valid_max :</span></dt><dd>120</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>description :</span></dt><dd>Channel number assigned for each received photon event. This is part of the photon ID. Values range from 1 to 120 to span all channels and rise/fall edges. Values 1 to 60 are for falling edge; PCE1 (1 to 20), PCE 2 (21 to 40) and PCE3 (41 to 60). Values 61 to 120 are for rising edge; PCE1 (61 to 80), PCE 2 (81 to 100) and PC3 (101 to 120).</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=uint8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>ph_id_count</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-524a1cb9-bd72-4efe-ad7d-54a5a3905907" class="xr-var-attrs-in" type="checkbox"><label for="attrs-524a1cb9-bd72-4efe-ad7d-54a5a3905907" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-b2e69bdc-09b3-4ebd-a522-547b2d588df9" class="xr-var-data-in" type="checkbox"><label for="data-b2e69bdc-09b3-4ebd-a522-547b2d588df9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>photon event counter</dd><dt><span>units :</span></dt><dd>counts</dd><dt><span>source :</span></dt><dd>Derived as part of Photon ID</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>description :</span></dt><dd>The photon event counter is part of photon ID and counts from 1 for each channel until reset by laser pulse counter.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=int8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>ph_id_pulse</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">uint8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-87b9d794-9309-4d07-a94f-e8354aea30b1" class="xr-var-attrs-in" type="checkbox"><label for="attrs-87b9d794-9309-4d07-a94f-e8354aea30b1" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-ecdda978-12ac-4169-a467-9ac0d6f7292f" class="xr-var-data-in" type="checkbox"><label for="data-ecdda978-12ac-4169-a467-9ac0d6f7292f" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>laser pulse counter</dd><dt><span>units :</span></dt><dd>counts</dd><dt><span>source :</span></dt><dd>Derived as part of Photon ID</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>description :</span></dt><dd>The laser pulse counter is part of photon ID and counts from 1 to 200 and is reset for each new major frame.</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=uint8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>quality_ph</span></div><div class="xr-var-dims">(delta_time)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-6fdf660c-b4bc-4e7e-9457-fa781d1e65e9" class="xr-var-attrs-in" type="checkbox"><label for="attrs-6fdf660c-b4bc-4e7e-9457-fa781d1e65e9" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-2451b2f0-0ae2-4c99-a9a7-ec8f0952b3f5" class="xr-var-data-in" type="checkbox"><label for="data-2451b2f0-0ae2-4c99-a9a7-ec8f0952b3f5" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Photon Quality</dd><dt><span>units :</span></dt><dd>1</dd><dt><span>source :</span></dt><dd>ATL03 ATBD</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>3</dd><dt><span>contentType :</span></dt><dd>qualityInformation</dd><dt><span>description :</span></dt><dd>Indicates the quality of the associated photon. 0=nominal, 1=possible_afterpulse, 2=possible_impulse_response_effect, 3=possible_tep. Use this flag in conjunction with signal_conf_ph to identify those photons that are likely noise or likely signal.</dd><dt><span>flag_meanings :</span></dt><dd>nominal possible_afterpulse possible_impulse_response_effect possible_tep</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3]</dd></dl></div><div class="xr-var-data"><pre>[19219882 values with dtype=int8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>signal_conf_ph</span></div><div class="xr-var-dims">(delta_time, ds_surf_type)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-592800fb-852b-428e-90ac-24655bda991a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-592800fb-852b-428e-90ac-24655bda991a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-02384821-1702-4ee2-9bf2-c2b4db676d1b" class="xr-var-data-in" type="checkbox"><label for="data-02384821-1702-4ee2-9bf2-c2b4db676d1b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Photon Signal Confidence</dd><dt><span>units :</span></dt><dd>1</dd><dt><span>source :</span></dt><dd>ATL03 ATBD, Section 5, Conf</dd><dt><span>valid_min :</span></dt><dd>-2</dd><dt><span>valid_max :</span></dt><dd>4</dd><dt><span>contentType :</span></dt><dd>qualityInformation</dd><dt><span>description :</span></dt><dd>Confidence level associated with each photon event selected as signal. 0=noise. 1=added to allow for buffer but algorithm classifies as background; 2=low; 3=med; 4=high).  This parameter is a 5xN array where N is the number of photons in the granule, and the 5 rows indicate signal finding for each surface type (in order: land, ocean, sea ice, land ice and inland water). Events not associated with a specific surface type have a confidence level of -1. Events evaluated as TEP returns have a confidence level of -2.</dd><dt><span>flag_meanings :</span></dt><dd>possible_tep not_considered noise buffer low medium high</dd><dt><span>flag_values :</span></dt><dd>[-2 -1  0  1  2  3  4]</dd></dl></div><div class="xr-var-data"><pre>[96099410 values with dtype=int8]</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-5a4a1ad2-6880-40b3-9109-67613ebc4709" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-5a4a1ad2-6880-40b3-9109-67613ebc4709" class="xr-section-summary">Attributes: <span>(2)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>Description :</span></dt><dd>Contains arrays of the parameters for each received photon.</dd><dt><span>data_rate :</span></dt><dd>Data are stored at the photon detection rate.</dd></dl></div></li></ul></div></div>
</div>
</div>
</section>
<section id="determine-variables-of-interest-sst-ocean-color-chemistry" class="level3">
<h3 class="anchored" data-anchor-id="determine-variables-of-interest-sst-ocean-color-chemistry">Determine variables of interest: SST, ocean color, chemistry…</h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CMR_OPS = 'https://cmr.earthdata.nasa.gov/search'</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># url = f'{CMR_OPS}/{"collections"}'</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(url, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'concept_id'</span>: <span class="st">'C1940475563-POCLOUD'</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'cloud_hosted'</span>: <span class="st">'True'</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> response.json()</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>variables <span class="op">=</span> response[<span class="st">'feed'</span>][<span class="st">'entry'</span>][<span class="dv">0</span>][<span class="st">'associations'</span>][<span class="st">'variables'</span>]</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>output_format <span class="op">=</span> <span class="st">"umm_json"</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>var_url <span class="op">=</span> <span class="st">"https://cmr.earthdata.nasa.gov/search/variables"</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(variables)):</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    response <span class="op">=</span> requests.get(<span class="ss">f"</span><span class="sc">{</span>var_url<span class="sc">}</span><span class="ss">.</span><span class="sc">{</span>output_format<span class="sc">}</span><span class="ss">?concept-id=</span><span class="sc">{</span>variables[i]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    response <span class="op">=</span> response.json()</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># print(response['items'][0]['umm'])</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'Name'</span> <span class="kw">in</span> response[<span class="st">'items'</span>][<span class="dv">0</span>][<span class="st">'umm'</span>]: pprint(response[<span class="st">'items'</span>][<span class="dv">0</span>][<span class="st">'umm'</span>][<span class="st">'Name'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="pull-those-variables-into-xarray-in-place" class="level3">
<h3 class="anchored" data-anchor-id="pull-those-variables-into-xarray-in-place">Pull those variables into xarray “in place”</h3>
<section id="first-we-need-to-determine-the-granules-returned-from-our-time-and-area-of-interest" class="level4">
<h4 class="anchored" data-anchor-id="first-we-need-to-determine-the-granules-returned-from-our-time-and-area-of-interest">First, we need to determine the granules returned from our time and area of interest</h4>
<div class="cell" data-execution_count="16">
<div class="sourceCode" id="cb26"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>gran_url <span class="op">=</span> <span class="ss">f'</span><span class="sc">{</span>CMR_OPS<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span><span class="st">"granules"</span><span class="sc">}</span><span class="ss">'</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(gran_url, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'concept_id'</span>: <span class="st">'C1940475563-POCLOUD'</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'temporal'</span>: temporal,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'bounding_box'</span>: bounding_box,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'page_size'</span>: <span class="dv">200</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.status_code)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.headers[<span class="st">'CMR-Hits'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>200
11</code></pre>
</div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode" id="cb28"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>modis_granules_meta <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> granule_meta <span class="kw">in</span> modis_granules_meta:</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(granule_meta[<span class="st">'boxes'</span>])</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(granule_meta[<span class="st">'links'</span>][<span class="dv">0</span>][<span class="st">'href'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>['63.232 157.13 88.897 180', '63.232 -180 88.897 -49.902']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622061001-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['68.267 -74.33 89.998 104.028']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-public/MODIS_T-JPL-L2P-v2019.0/20190622093001-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc.md5
['68.29 -100.13 89.998 79.455']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622111001-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['65.983 -125.049 89.998 54.765']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622125000-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['64.671 -149.702 89.996 30.029']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622142500-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['63.327 -130.186 89.093 27.231']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622143000-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['67.198 -173.585 89.996 5.195']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622160501-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['60.312 -112.093 85.084 -9.865']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-public/MODIS_T-JPL-L2P-v2019.0/20190622161000-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc.md5
['69.227 170.467 89.994 180', '69.227 -180 89.994 -27.697']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622174501-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc
['67.177 144.606 89.998 180', '67.177 -180 89.998 -53.628']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-public/MODIS_T-JPL-L2P-v2019.0/20190622192501-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc.md5
['63.354 -65.91 89.07 91.026']
https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-public/MODIS_T-JPL-L2P-v2019.0/20190622210001-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc.md5</code></pre>
</div>
</div>
<div class="cell" data-execution_count="37">
<div class="sourceCode" id="cb30"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>https_link <span class="op">=</span> modis_granules_meta[<span class="dv">0</span>][<span class="st">'links'</span>][<span class="dv">0</span>][<span class="st">'href'</span>]</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>s3_link <span class="op">=</span> https_link.replace(<span class="st">'https://archive.podaac.earthdata.nasa.gov/'</span>,<span class="st">'s3://'</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>s3_link</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display" data-execution_count="37">
<pre><code>'s3://podaac-ops-cumulus-protected/MODIS_T-JPL-L2P-v2019.0/20190622061001-JPL-L2P_GHRSST-SSTskin-MODIS_T-D-v02.0-fv01.0.nc'</code></pre>
</div>
</div>
</section>
</section>
<section id="get-s3-credentials" class="level3">
<h3 class="anchored" data-anchor-id="get-s3-credentials">Get S3 credentials</h3>
<div class="sourceCode" id="cb32"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>s3_credentials <span class="op">=</span> requests.get(<span class="st">'https://archive.podaac.earthdata.nasa.gov/s3credentials'</span>).json()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb33"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>s3_fs <span class="op">=</span> s3fs.S3FileSystem(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    key<span class="op">=</span>s3_credentials[<span class="st">"accessKeyId"</span>],</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    secret<span class="op">=</span>s3_credentials[<span class="st">"secretAccessKey"</span>],</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    token<span class="op">=</span>s3_credentials[<span class="st">"sessionToken"</span>],</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="open-a-s3-file" class="level3">
<h3 class="anchored" data-anchor-id="open-a-s3-file">Open a s3 file</h3>
<div class="sourceCode" id="cb34"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> s3_fs.<span class="bu">open</span>(s3_link)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> xr.open_dataset(f, engine<span class="op">=</span><span class="st">'h5netcdf'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="use-geolocation-of-icesat-2-to-define-the-single-transect-used-to-pull-coincident-ocean-data-out-from-array" class="level3">
<h3 class="anchored" data-anchor-id="use-geolocation-of-icesat-2-to-define-the-single-transect-used-to-pull-coincident-ocean-data-out-from-array">Use geolocation of ICESat-2 to define the single transect used to pull coincident ocean data out from array</h3>
</section>
<section id="create-a-plot-of-the-single-transect-of-gridded-data" class="level3">
<h3 class="anchored" data-anchor-id="create-a-plot-of-the-single-transect-of-gridded-data">Create a plot of the single transect of gridded data</h3>
<p>(bonus: time series) - describe what this means to egress out of the cloud versus pulling the original data down (benefit to processing in the cloud)</p>
</section>
</section>
<section id="download-modis-ghrsst-data-from-cloud" class="level2">
<h2 class="anchored" data-anchor-id="download-modis-ghrsst-data-from-cloud">Download MODIS GHRSST data from Cloud</h2>
<div class="sourceCode" id="cb35"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shapely.geometry <span class="im">import</span> box</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb36"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>map_proj <span class="op">=</span> ccrs.PlateCarree()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb37"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bbox_geometry(boxs, t_crs<span class="op">=</span>ccrs.NorthPolarStereo()):</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''Generates a shapely.geometry.box object from boxes metadata'''</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    lat_min, lon_min, lat_max, lon_max <span class="op">=</span> [<span class="bu">float</span>(v) <span class="cf">for</span> v <span class="kw">in</span> bbox.split()]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    x_min, y_min <span class="op">=</span> t_crs.transform_point(lon_min, lat_min, ccrs.PlateCarree())</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    x_max, y_max <span class="op">=</span> t_crs.transform_point(lon_max, lat_max, ccrs.PlateCarree())</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> box(x_min, y_min, x_max, y_max)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>bbox_features <span class="op">=</span> []</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> granule <span class="kw">in</span> modis_granules_meta:</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> bbox <span class="kw">in</span> granule[<span class="st">'boxes'</span>]:</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>        bbox_features.append(bbox_geometry(bbox))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-execution_count="27">
<div class="sourceCode" id="cb38"><pre class="sourceCode python cell-code code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">7</span>,<span class="dv">7</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot(projection<span class="op">=</span>ccrs.NorthPolarStereo())</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>ax.set_extent([<span class="op">-</span><span class="fl">180.</span>,<span class="fl">180.</span>,<span class="fl">60.</span>,<span class="fl">90.</span>], ccrs.PlateCarree())</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>ax.coastlines()</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>ax.add_geometries([bbox_features[<span class="dv">0</span>]], crs<span class="op">=</span>map_proj, alpha<span class="op">=</span><span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display" data-execution_count="27">
<pre><code>&lt;cartopy.mpl.feature_artist.FeatureArtist at 0x7efcbee4b580&gt;</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Data_Access__Harmonize-cloud-non-cloud_andy_to_avoid_merge_conflicts_files/figure-html/cell-31-output-2.png" class="img-fluid"></p>
</div>
</div>
<hr>
</section>
<section id="resources-optional" class="level2">
<h2 class="anchored" data-anchor-id="resources-optional">Resources (optional)</h2>
<hr>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>


</section>
</section>
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('div.sidebar-toc .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
    } else {
      disableStylesheet(alternateStylesheets);
    }
    manageTransitions('.quarto-toc-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      return window.localStorage.getItem("quarto-color-scheme");
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = null;
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.id = "quarto-color-scheme-toggle";
    a.classList.add('top-right');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    setTimeout(function() {
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    window.tippy(el, {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    }); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</main>
<div class="page-navigation page-navigation-docked">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
  </div>
</div>
</div> <!-- /main column -->
</div> <!-- /row -->
<div class="row">
  <div class="nav-footer">
      <div class="nav-footer-center me-auto ms-auto">PODAAC, NSIDC DAAC and LPDAAC (2021). 2021 Cloud Hackathon</div>
  </div>
</div>
</div> <!-- /container fluid -->


</body></html>